export * from './IFunctionalityUser'
export * from './ICreateFunctionalityUser'
export * from './IFunctionalityUserRepo'
export * from './IUpdateFunctionalityUser'
export * from './IListFunctionalityUser'
