enum ErrorCode {
    NOT_FOUND = 'NOT_FOUND',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    PARAMS_REQUIRED = 'PARAMS_REQUIRED',
    FIELD_REQUIRED = 'FIELD_REQUIRED',
    INVALID_VALUE = 'INVALID_VALUE',
    INVALID_OPTION = 'INVALID_OPTION',
    INVALID_FIELD = 'INVALID_FIELD',
  }
  
  export { ErrorCode }
  